apiVersion: apps/v1
kind: Deployment
metadata:
  name: money-management
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: money-management
          resources:
            requests:
              cpu: '100m'
              memory: '128Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
          env:
            - name: NODE_ENV
              value: 'development'
            - name: PORT
              value: '5005'
