apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: client
          resources:
            requests:
              cpu: '200m'
              memory: '256Mi'
            limits:
              cpu: '1000m'
              memory: '1Gi'
          env:
            - name: NODE_ENV
              value: 'production'
            - name: NEXT_PUBLIC_API_URL
              value: 'https://api.soranix.com'
