apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: soranix

resources:
  - notification-service.yaml

commonLabels:
  app.kubernetes.io/name: soranix
  app.kubernetes.io/part-of: soranix-platform
  app.kubernetes.io/managed-by: kustomize





