apiVersion: v1
kind: Service
metadata:
  name: bills-payment-service
  namespace: soranix
  labels:
    app: bills-payment
    tier: backend
spec:
  selector:
    app: bills-payment
    tier: backend
  ports:
    - name: http
      port: 80
      targetPort: 5007
      protocol: TCP
  type: ClusterIP





