
    upstream client {
        server soranix-client:3000;
    }

    upstream auth {
        server soranix-auth:5001;
    }

    server {
        client_max_body_size 20M;
        listen 80;

        location / {
            proxy_pass http://client;
            proxy_set_header  X-Real-IP  $remote_addr;

        }

        location /api/v1/auth {
            proxy_pass http://auth;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header Host $host;
            proxy_redirect off;
        }

        location /api/v1/users {
            proxy_pass http://auth;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header Host $host;
            proxy_redirect off;
        }

        # Health check endpoint
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }
