---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: soranix-sa
  namespace: soranix
  labels:
    app: soranix
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: soranix-role
  namespace: soranix
rules:
  - apiGroups: ['']
    resources: ['pods', 'services', 'endpoints', 'configmaps', 'secrets']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete']
  - apiGroups: ['apps']
    resources: ['deployments', 'replicasets']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete']
  - apiGroups: ['networking.k8s.io']
    resources: ['ingresses', 'networkpolicies']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: soranix-role-binding
  namespace: soranix
subjects:
  - kind: ServiceAccount
    name: soranix-sa
    namespace: soranix
roleRef:
  kind: Role
  name: soranix-role
  apiGroup: rbac.authorization.k8s.io
