apiVersion: v1
kind: Service
metadata:
  name: money-management-service
  namespace: soranix
  labels:
    app: money-management
    tier: backend
spec:
  selector:
    app: money-management
    tier: backend
  ports:
    - name: http
      port: 80
      targetPort: 5005
      protocol: TCP
  type: ClusterIP





