apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: soranix
  labels:
    app: payments
    tier: backend
spec:
  selector:
    app: payments
    tier: backend
  ports:
    - name: http
      port: 80
      targetPort: 5003
      protocol: TCP
  type: ClusterIP





