apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: soranix
  labels:
    app: admin
    tier: frontend
spec:
  selector:
    app: admin
    tier: frontend
  ports:
    - name: http
      port: 80
      targetPort: 3001
      protocol: TCP
  type: ClusterIP





