apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: soranix

resources:
  - namespace.yaml
  - rbac.yaml
  - network-policies.yaml
  - config.yaml
  - hpa.yaml
  - httproute-frontend.yaml
  - httproute-api.yaml

commonLabels:
  app.kubernetes.io/name: soranix
  app.kubernetes.io/part-of: soranix-platform
  app.kubernetes.io/managed-by: kustomize





