name: Build Docker Image on Pull Request

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/client/Dockerfile # Change this path to your service's Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/soranix-client:pr-${{ github.event.pull_request.number }}

      # Optionally, you can add a step to run tests or scan the image here