apiVersion: v1
kind: Service
metadata:
  name: flows-service
  namespace: soranix
  labels:
    app: flows
    tier: backend
spec:
  selector:
    app: flows
    tier: backend
  ports:
    - name: http
      port: 80
      targetPort: 5009
      protocol: TCP
  type: ClusterIP





